phraseapp:
  project_id: "443787b2c67e387acfcde98617b6899e"
  file_format: "strings"
  push:
    sources:
    - file: "HelloWorld/<locale_code>/Localizable.strings"
      params:
        file_format: "strings"
  pull:
    targets:
    - file: "HelloWorld/<locale_code>/Localizable.strings"
